{
    "name": "Library Application",
    "summary": "Information about Libary",
    "author": "bizzappdev",
    "website": "https://bizzappdev.com",
    "category": "uncategorized",
    "version": "15.0.1.0.0",
    "depends": ["base", "mail"],
    "data": [
        "data/ir_sequence_data.xml",
        "data/ir_config_parameter.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/book_tag_views.xml",
        "views/book_details_views.xml",
        "views/borrower_details_views.xml",
        "views/library_menu_views.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
