from . import student_details  # noqa: F401
from . import teachers_details  # noqa: F401
from . import course_details  # noqa: F401
from . import subject_details  # noqa: F401
from . import exam_details  # noqa: F401
from . import result_details  # noqa: F401
from . import library_details  # noqa: F401
from . import res_config_settings  # noqa: F401
from . import activity_details  # noqa: F401
