{
    "name": "School Management",
    "summary": "Information about School",
    "author": "bizzappdev",
    "website": "https://bizzappdev.com",
    "category": "uncategorized",
    "version": "15.0.1.0.0",
    "depends": ["base"],
    "data": [
        "data/ir_sequence_data.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings.xml",
        "views/activity_details_views.xml",
        "views/library_details_views.xml",
        "views/result_details_views.xml",
        "views/exam_details_views.xml",
        "views/course_details_views.xml",
        "views/subject_details_views.xml",
        "views/teachers_details_views.xml",
        "views/student_details_views.xml",
        "views/school_menu_views.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
